version: '3.7'

services:
  web:
    build: .
    volumes:
      - .:/docker-done-right:cached
      - bundle_cache:/bundle_cache
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - mongo
    environment:
      BUNDLE_PATH: /bundle_cache
      GEM_HOME: /bundle_cache
      GEM_PATH: /bundle_cache
      RAILS_PORT: 3000
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      MONGODB_HOST: mongo
    stdin_open: true
    tty: true
    command: bash

  postgres:
    image: postgres:14.1-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    restart: always

volumes:
  bundle_cache:
  mongo_data:
  pg_data:
